feat: 일단 커밋
Team-Fundy/Fundy-Server pull request #12
Opened 2023-12-31 15:00 UTC by dmo2595

✨  Summary
---------------------------------------
코드 진행중
점검 받을려고 올림

🔑  Key Point
---------------------------------------
코드 안되는 코드입니다.

🙏🏼  To Reviewer
---------------------------------------
새해복 많이 받으십쇼

✅ PR Checklist
---------------------------------------
- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 이전의 기능들을 포함하여 모든 기능이 완전히 작동하는지 확인했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.

2024-01-02 01:15 UTC, EastWon0103 reviewed
## 코드 리뷰 결과
- DB에 대한 이해 필요 (id, foreign key, sql 등등)
- Transactional 오사용
- 소소한 네이밍 문제
- 프로젝트의 dependency에 대한 생각 미흡

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/build.gradle
> +        api project(":domain:devnote")
일단 잘하셨습니다.
다만 api와 implementation의 차이가 무엇인지 생각해보면 좋을 것 같습니다.
그리고 왜 사용했는지 의도를 알게 되면 댓글 남겨주세요.

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/DevNoteService.java
> +
@Transactional을 다시 붙이는 이유는 기존의 readOnly=True 옵션을 readOnly=False로 덮어쓰기 위함입니다.
물론 작동은 되겠지만 성능상 읽기만 존재하면 @Transactional을 삭제하시는 게 좋습니다.

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/DevNoteFindByIdUseCase.java
> +}
## 파라미터
findById는 Id를 통해서 devnote를 찾는 것입니다. 파라미터는 id로만으로도 충분합니다.

## 네이밍
메서드 명은 괜찮으나, DTO는 조금 더 명확하게 쓰는 것이 좋을 것 같습니다.
FindByIdResponse나 FindByIdRequest는 다른 곳에서도 똑같이 사용할 수 있습니다. 
만약 저였더라면 DevNoteFindById...로 작명했을 것 같습니다.

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/req/FindByIdRequest.java
> +}
## DTO
지금 하는 일은 id로 devnote를 찾는 것입니다. 굳이 DTO로 할 필요는 없습니다.
어쩔 때 DTO를 사용하는 것이 좋을지 생각해보시면 좋을 것 같습니다.

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/res/FindByIdResponse.java
> +}
## Name
아까 말했던 Naming이 올바르지 않습니다.

## Field
title / contents / projectId말고 더 필요한 것이 있지 않을까요?
가령 작성일 같은 것들 말이죠

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/out/LoadDevNotePort.java
> +    Optional<DevNote> findById(String id);
## ID
DB의 ID는 무엇을 사용하는 것이 좋을까요? 보통 두 가지의 ID를 사용합니다.
#### big int auto increment(= 자바에선 Long)
보통 주로 쓰는 id 옵션입니다. 특징은 db에서 정수형으로 저장되며, 지정하지 않고 저장 시 알아서 id 값을 올려주어 저장합니다.
```sql
insert into devnote (id, title, content) values(1,"타이틀", "콘텐츠");
-- 1, "타이틀", "콘텐츠"가 저장됨
insert into devnote (title, content) values("타이틀2", "콘텐츠2");
-- 2, "타이틀2", "콘텐츠2"가 저장됨
```
매우 편하지만 다음 값을 예측할 수 있다는 단점이 존재합니다. 예를 들어 페이지 url이 www.fundy.com/devnote/1022이 있으면 www.fundy.com/devnote/56도 있을 수 있다고 가정할 수 있습니다.     
그렇기 때문에 크롤링 혹은 유추가 매우 쉬운 구조여서 민감한 정보인 경우에는 이 옵션이 좋지 않습니다.


#### UUID
id를 'adfajfdlajdf-jklfjdkalf-fadfadf'와 같은 무작위 포맷으로 생성합니다. 중복될 확률은 매우 낮습니다. 아까 말씀드린 유추가 어렵게 하여 보안성을 높일 수 있습니다.   
하지만 db의 읽기 / 쓰기 값이 매우 증가하는 단점을 가지고 있습니다. (이유는 id를 통해 CRUD 작업이 일어납니다.)

### Result
개발 노트는 모두에게 열려 있는 서비스 입니다. 로그인을 안해도 볼 수 있습니다(일단은). 보안성 보다는 읽기 / 쓰기 성능의 장점을 챙기는 것이 좋아 보여 id를 big int를 쓰는 것이 좋아보입니다.

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/out/LoadDevNotePort.java
> +    Optional<DevNote> findById(String id);
그래서 String을 쓰는 이유는 없다고 생각합니다. Long으로 대체 해주세요.(db의 big int auto increment id를 사용하기 위해서)

2024-01-02 01:15 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/out/ValidDevNotePort.java
> +    boolean existById(String id);
id 타입 수정해주세요

2024-01-02 01:15 UTC, EastWon0103 commented on conf/mysql/init-sql/010_devnote.sql
> +);
## id 누락
db는 특정 데이터를 찾기 위해 id가 필요로 합니다. id는 모든 데이터를 분류할 수 있도록 unique(각각 값이 다른) 하고 null이 될 수 없는 특성을 가지고 있습니다.

## Type
varchar말고 다양한 타입들이 존재합니다. 개발노트에 필요한 타입을 사용하는 것이 좋을 것 같습니다.

## likes
like의 정보를 하나의 속성 타입으로 정의가 가능할까요? 어떤 유저가 어디에 좋아했는지 등의 정보가 담겨 있어야 합니다. 그러면 좋아요 수는 어떻게 계산할 수 있을까요? 일단은 foreign key로 연결하여 계산할 수 있습니다.
```sql
-- 만약 인스타그램 페이지가 있고 좋아요 수가 있다는 가정 (사진은 편의를 위해 한 장만)
CREATE table fundy_user
(
  id bigint not null auto_increment primary key,
  nickname varchar(255) not null
);

create table page
(
  id bigint not null auto_increment primary key,
  content varchar(255) not null,
  image varchar(255) not null,
  owner_id bigint not null,
  foreign key  (owner_id) references fundy_user (id)
);

create table page_like
(
  id bigint not null auto_increment primary key,
  page_id bigint not null,
  user_id bigint not null,
  foreign key  (page_id) references page (id),
  foreign key  (user_id) references fundy_user (id)
);

insert into fundy_user (id, nickname)
values (1,"유저1"), (2,"유저2"), (3,"유저3"), (4,"유저4");

insert into page(id, content, image, owner_id)
values (1,"content", "image", 1),
(2,"content", "image", 1);

insert into page_like(page_id, user_id)
values (1,4), (1,2), (1,3), (2,2), (2,3);

-- SQL 딴에서 좋아요 수 계산
select p.id, p.content, p.image, p.owner_id, count(l.id) as likes
from page p
left join page_like l
on p.id = l.page_id
group by p.id

-- 결과
-- id	content	image	owner_id	      likes
-- 1	content	image	1	              3
-- 2	content	image	1	              2
```

혹은 Data Jpa와 같이 활용하여 사용할 수 있습니다.
```java
class DevNote {
    // 나머지는 생략
    private List<DevNoteLike> devNoteLikes = new ArrayList<>();
}

DevNote devNote = // 생략
int devNoteLikes = devNote.getDevNoteLikes.size();
```


우선은 likes를 테이블에서 빼고 진행하면 될 것 같습니다.

2024-01-02 01:15 UTC, EastWon0103 commented on domain/devnote/build.gradle
> +        implementation 'org.springframework.security:spring-security-crypto:6.2.1'
왜 이 라이브러리 / 모듈이 필요한가 생각해야 합니다. 
`domain:user`에서는 비밀번호 암호화를 위하여 해당 `'org.springframework.security:spring-security-crypto:6.2.1'`의 dependency가 필요했습니다.
개발노트는 필요 없으니 빼줍시다.

2024-01-02 01:15 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/mapper/DevNoteMapper.java
> +public class DevNoteMapper {
일단은 넘어가겠습니다.

2024-01-02 01:15 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/model/DevNoteModel.java
> +    @Id
ID와 db 테이블을 모두 수정하고 반영해주세요

2024-01-02 06:42 UTC, dmo2595 commented on application/devnote-service/build.gradle
> +        api project(":domain:devnote")
api - 해당 모듈을 의존하는 모든 모듈을 가져온다
implementation - 해당 모듈만 가져온다
이 차이가 맞을까요?
그래서 api로 되어있는 것을 implementation으로 변경해야 알맞은 조치가 될까요?

2024-01-02 06:43 UTC, dmo2595 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/DevNoteService.java
> +
삭제했습니다

2024-01-02 07:16 UTC, EastWon0103 commented on application/devnote-service/build.gradle
> +        api project(":domain:devnote")
## API vs Implementation
자세한 내용: https://jongmin92.github.io/2019/05/09/Gradle/gradle-api-vs-implementation/

적어주신 내용은 대강 맞습니다.    
하지만 제일 중요한 것은 `왜` 그렇게 해놨는지가 중요합니다.
그리고 이 부분은 `output port`와 직접적인 관련이 있습니다.

## Why
devnote-service에서는 devnote라는 도메인 모델을 사용합니다. 이는 devnote 모듈을 의존성에 추가하여 사용합니다.   
그리고 output port를 통해서 도메인 모델을 return하게 짜게 됩니다. 그러다 보니 다음과 같은 Output Port가 작성되게 됩니다.
```java
Optional<DevNote> findById(Long id);
```

이 port를 구현하는 `output adapter`는 `devnote-service`에 `dependency`가 생기게 됩니다. 하지만 `devnote-service`에서 `devnote 모듈`을 `implemenation`로 가져오게 된다면 `output adapter`는 `DevNote`가 무엇인지 모르게 됩니다.

그렇기 때문에 `api`를 써서 `devnote-service 모듈`을 사용하는 타 모듈에서도 `DevNote`를 사용할 수 있도록  구성한 것 입니다.    

## Question
여기서 추가적으로 궁금하실 수 있는 사항은 완벽히 `"데이터 및 도메인 로직에 관해서 정보 은닉이 불가능하지 않는가?"` 입니다   
맞습니다. 결과적으로 `output-adapter`에서 도메인 로직을 알고 사용하는 것은 좋지 못한 설계 입니다. 그렇기 때문에 이 부분은 `DTO`로 대체하여 데이터만을 이동시킬 수 있습니다.
```java
Optional<DevNoteResponse> findById(Long id);
```

하지만 이럴 경우 `output adapter`에서는 `DevNoteModel(영속성 모델)`을 `DevNoteResponse`에 매핑 시키고 `service`에서는 `DevNoteResponse`를 `DevNote` 모델에 매핑시켜야 한다는 번거로운 작업이 존재합니다. 그리고 이 과정에서 추가적인 `마셜링 / 언마셜링`이 발생하여 오버헤드가 발생합니다. (마셜링 / 언마셜링은 궁금하시면 따로 찾아보세요~!)

그렇기 때문에 저희 프로젝트에서는 일단은 `도메인 로직의 정보 은닉을 포기`하고 `편의성`을 택했다고 생각하시면 되겠습니다.

물론 `output adapter`에서 영속성 모델과 도메인 모델 간의 매핑을 할 때, 왠만하면 `도메인 로직을 사용하지 않고 mapping`만 시키는 것에 집중해야 되겠습니다.

## 결과
고치실 필요 없습니다.

2024-01-05 03:34 UTC, EastWon0103 requested changes
## 코드 리뷰 24.01.05
- dependency 설정
- jpa-adpater 미완료
- API 문서화 필요
- 기타 수정(DTO 명칭 등등)

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/build.gradle
> +    implementation project(path: ':output:jpa-adapter')
## dependency
`devnote-service`에는 `output:jpa-adapter`가 필요 없습니다.
그리고 해당 `dependency`의 경우에는 아래의 정의가 되어 있으므로 삭제해주세요

## 'org.springframework.boot:spring-boot-starter-web'
그리고 해당 부분이 변경되었습니다. 다음 커밋시 메인을 풀 받고 해당 부분을
`implementation "org.springframework:spring-context"`으로 대체해주세요
> 아직 main 브랜치에 적용이 안되었으므로 제가 main push하게 되면 연락드리겠습니다.

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/DevNoteService.java
> +        DevNote devNote = devNotePersistenceAdapter.findById(id).orElseThrow(() -> new RuntimeException("No DevNote"));
## RuntimeException
`RuntimeException`인 경우에는 `api-adapter`의 `ExceptionHandler`에서 처리하기 힘들어집니다. 
왜냐하면 `RuntimeException`은 `IllegalArgumentException` 등 `Unchecked Exception`의 상위 `Exception`이기 때문입니다.   
그렇기 때문에 만약에 `커스텀 Exception`(RuntimeException을 상속함)을 쓰더라도 `RuntimeException`으로 우선적으로 처리되어, 예외 발생 시 응답의 커스텀이 힘들어지게 됩니다.

해당 예외의 경우에는 `core-exception 모듈`의 `NoInstanceException`을 사용해주세요.

자바의 Exception에 대한 설명은 다음을 참고해주세요.
https://dreamcoding.tistory.com/70

## DevNotePersistenceAdapter
아까와 같이 DIP가 지켜지지 않았습니다.`devNotePersistenceAdapter`라는 구현체를 사용하는 것이 아니라 `LoadDevNotePort`와 같이 인터페이스를 사용해야 합니다.

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/DevNoteService.java
> +    private final DevNotePersistenceAdapter devNotePersistenceAdapter;
## DIP
DevNotePersistenceAdapter를 직접적으로 사용할 필요가 없습니다.
DevNotePersistenceAdapter가 있는지를 모르게 하는 것이 키 포인트 입니다.
DevNotePersistenceAdapter를 삭제해주시고, 궁금한 점은 댓글 부탁드립니다.

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/req/FindByIdRequest.java
>  public class FindByIdRequest {
DTO를 삭제해주세요

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/res/FindByIdResponse.java
> -    private Long projectId;
개발노트에서는 이보다 더 많은 내용이 필요합니다

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/req/FindByIdRequest.java
>  }
해당 파일이 왜 남아있는지?

2024-01-05 03:34 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/res/FindByIdResponse.java
>  public class FindByIdResponse {
## Response명
말씀드렸던 것처럼 명칭을 보고 무엇을 뜻하는지 알 수 있어야 합니다.
개발노트 상세적인 부분을 조회하는 것이니 DevNoteDetailResponse로 고쳐보는 것은 어떨까요?

2024-01-05 03:34 UTC, EastWon0103 commented on conf/mysql/init-sql/010_devnote.sql
> +    likes int
저번에 말씀드린 것 처럼 likes는 스키마에서 도출되는 것이 아닙니다. 삭제해주세요

2024-01-05 03:34 UTC, EastWon0103 commented on input/api-adapter/build.gradle
>      bootJar{enabled = true}
dependency는 프로젝트 괄호 안에 기술해주세요

2024-01-05 03:34 UTC, EastWon0103 commented on input/api-adapter/src/main/java/com/fundy/api/controller/devnote/DevNoteController.java
> +    @GetMapping("/{id}")
## API 명세서 작성
이제는 API 명세서를 작성할 줄 알아야 합니다. 다음 시간에 문서화를 진행해보도록 하죠

2024-01-05 03:34 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/adapter/DevNotePersistenceAdapter.java
> +    public boolean existById(Long id) {
전체적으로 구현 내용이 존재하지 않네요. repository를 활용하여 구축해보세요

2024-01-24 11:35 UTC, EastWon0103 reviewed
## 24/01/24 코드리뷰
- 통합 테스트 부분 수정
- 필요없는 부분이 존재
- TODO 주석 활용

2024-01-24 11:35 UTC, EastWon0103 commented on input/api-adapter/src/test/java/com/fundy/api/controller/devnote/DevNoteControllerTest.java
> +        String title = "Test title";
## 통합 테스트 데이터
저장이 안되었는데 어떻게 테스트를 통과했나요? 혹시 DB에 임의로 값을 집어넣으신 건가요?
테스트는 어느 코드나 어떤 상황에서도 동작해야합니다. 만약 저라면 `DevNoteRepository`를 이용해 임시로 데이터를 저장했을 것 같습니다.
> 참고로 통합 테스트에서는 데이터 저장 이후 Transactional로 처리되어 다시 롤백 됩니다.

2024-01-24 11:35 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/adapter/DevNotePersistenceAdapter.java
> +    //저장할 거 추가 필요
## TODO 주석 사용하기
이렇게 주석을 사용하면 주석을 깜빡할 수 있습니다. 만약 주석을 까먹지 않아야 하는 경우`TODO` 주석 혹은 `FIXME` 주석을 사용하시길 바랍니다. 해당 주석들은 인텔리제이에서 확인하여 어디서 해당 주석이 쓰였는지 확인할 수 있어 편합니다.
```java
// 예시
// TODO: 저장할 거 추가 필요
// FIXME: 여기 type Long -> String으로 변환
```

2024-01-24 11:35 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/mapper/DevNoteMapper.java
> +//일단 따라함 수정 필요
해당 주석의 경우도 나중을 위해 FIXME 주석을 달아보세요

2024-01-24 11:35 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/in/dto/req/SaveDevNoteRequest.java
> +}
## 필요하지 않은 id, createdAt
`mysql`에서 `devnote`의 `id`는 `bigint auto_increment`로 `id값을 자동`으로 설정됩니다.  또한 `createdAt`의 default값으로 `current_timestamp`가 들어갑니다. 그렇기에 해당 컬럼이 insert되지 않아도 `자동으로 현재 날짜/시간`을 넣어 주게 됩니다.
아마도 devnote를 새로 삽입하는 쿼리는 다음과 같을 것으로 예상됩니다.
```mysql
insert into devnote(title, content)
values ("타이틀 예시", "콘텐츠 예시")
```
## Data JPA에서 insert 쿼리 (+repository.save()의 과정)
만약 해당 쿼리 처럼 나가도록 하기 위해서는 어떻게 해야할까요? 결과는 `@DynamicInsert` 어노테이션입니다. 해당 어노테이션이 영속성 모델 객체 (DevNoteModel)이 붙어 있으면 새로운 객체를 repository를 통해 save()하게 된다면 앞서 기재한 쿼리처럼 실행됩니다. (하지만 id는 조금 다르게 실행되긴 합니다. @DynamicInsert를 붙이지 않고 id를 넣지 않아도 id가 자동으로 설정되는 것 처럼요!) 

결론: id와 createdAt을 넣을 필요가 없다.

### +repository.save()의 과정(심화)
계속 해보면 알겠지만 repository 인터페이스의 save()는 새로운 객체를 저장할 때만 사용하는 것이 아니라, 객체를 업데이트할 때도 사용됩니다. 어떻게 해당 작업들을 처리할 수 있는 걸까요? 그 이유는 save가 내부적으로 아래와 같이 작동되기 때문입니다.
(객체의 id가 주어진 상태에서 save) -> id에 맞는 객체를 찾음 -> 저장하려는 객체와 이미 저장되어 있는 객체 비교해서 업데이트
(객체의 id가 주어지지 않았을 때 save) -> 객체를 저장 (id는 자동생성)

그렇기 때문에 만약 새로운 객체를 저장하려고 해도 id값이 주어지만 해당 id의 객체가 있는지 조사하는 쿼리를 날리기 때문에 새로 저장 시에는 id 값이 없는 객체를 저장해야 합니다. 자세한 내용은 아래 링크를 참고해 주세요
참고: https://velog.io/@rainmaker007/spring-data-jpa-save-%EB%8F%99%EC%9E%91-%EC%9B%90%EB%A6%AC
## 추가적으로 thumbnail이 빠졌습니다.
## persistenceAdapter를 보니 실제로는 id와 createdAt은 사용하지 않는 것을 확인했습니다. 그래도 해당 지적사항들은 수정해주세요

2024-01-24 11:35 UTC, EastWon0103 commented on application/devnote-service/src/main/java/com/fundy/application/devnote/out/command/SaveDevNoteCommand.java
> +}
앞서 말한 것처럼 id와 createdAt은 불필요합니다.

2024-01-24 11:35 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/adapter/DevNotePersistenceAdapter.java
> +        return true;
여기도 까먹지 않기 위기 위해 고쳐야 합니다. 참고로 existsById는 id를 가지고 있는 데이터가 존재하면 true, 없으면 false입니다.

2024-01-24 11:35 UTC, EastWon0103 commented on output/jpa-adapter/src/main/java/com/fundy/jpa/devnote/model/DevNoteModel.java
> +    }
아마 더 많은 내용이 들어갈 수도 있습니다. 일단 고치지 말고 나중에 수정해주세요

2024-01-25 13:15 UTC, EastWon0103 requested changes
## Response id 추가
이게 마지막 request

2024-01-25 13:22 UTC, EastWon0103 approved these changes

2024-01-25 16:11 UTC, merged